// Namespace-Exporte: die shadcn-Bausteine exportieren durchweg gleiche Namen
// (Root, Trigger, Content, …) — ein flacher Sammel-Export kollidiert deshalb.
// Direkte Unterpfad-Importe sind weiterhin moeglich und erzeugen kleinere
// Bundles: import { Button } from "@compdata/ui/button";
export * as AppShell from "./app-shell/index.js";
export * as AsyncBlock from "./async-block/index.js";
export * as Avatar from "./avatar/index.js";
export * as Badge from "./badge/index.js";
export * as BooleanIcon from "./boolean-icon/index.js";
export * as Breadcrumb from "./breadcrumb/index.js";
export * as Button from "./button/index.js";
export * as Card from "./card/index.js";
export * as Checkbox from "./checkbox/index.js";
export * as Collapsible from "./collapsible/index.js";
export * as CollapsibleText from "./collapsible-text/index.js";
export * as ConfirmDialog from "./confirm-dialog/index.js";
export * as CountBadge from "./count-badge/index.js";
export * as DetailShell from "./detail-shell/index.js";
export * as DevOnly from "./dev-only/index.js";
export * as Drawer from "./drawer/index.js";
export * as DropdownMenu from "./dropdown-menu/index.js";
export * as Field from "./field/index.js";
export * as Input from "./input/index.js";
export * as Label from "./label/index.js";
export * as Labels from "./labels/index.js";
export * as List from "./list/index.js";
export * as LoadingIndicator from "./loading-indicator/index.js";
export * as Modal from "./modal/index.js";
export * as Popover from "./popover/index.js";
export * as Progress from "./progress/index.js";
export * as SectionLabel from "./section-label/index.js";
export * as Select from "./select/index.js";
export * as Separator from "./separator/index.js";
export * as Sheet from "./sheet/index.js";
export * as Sidebar from "./sidebar/index.js";
export * as SignatureField from "./signature-field/index.js";
export * as Skeleton from "./skeleton/index.js";
export * as Sonner from "./sonner/index.js";
export * as Spinner from "./spinner/index.js";
export * as Table from "./table/index.js";
export * as Tabs from "./tabs/index.js";
export * as Textarea from "./textarea/index.js";
export * as Tooltip from "./tooltip/index.js";
